id: P002978
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:13.381852
source_metadata:
  id: bdr:W1KG12303
  title: རིག་གནས་ལྔའི་རྣམ་གཞག་གསལ་བར་སྟོན་པ་བློ་གྲོས་པདྨོ་བཞད་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    9a292f9ad16f4fa687a0dffb111fbf80:
      image_group_id: I1KG12320
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
