id: I0795D59E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:19:28+00:00'
last_modified: '2022-06-07T16:43:38.003912+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12303
  title: རིག་གནས་ལྔའི་རྣམ་གཞག་གསལ་བར་སྟོན་པ་བློ་གྲོས་པདྨོ་བཞད་པའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3DBD:
      image_group_id: I1KG12320
      title: ''
      total_pages: 100
      order: 1
      base_file: 3DBD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
